version: '3.9'

services:
  django:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    container_name: panda_container
    image: panda:1.0
    ports:
      - 8000:8000